# This is a basic workflow to help you get started with Actions

name: ager

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            Get-Localuser
            REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
            cmd /c "net user Administrator @RDPfree /add"
            cmd /c "net localgroup administrators Administrator /add"
            cmd /c "net user Administrator /active:yes"
            cmd /c "net user installer /delete"
            cmd /c "ICACLS C:\Windows\Temp /grant Administrator:F"
            cmd /c "ICACLS C:\Windows\Installer /grant Administrator:F"
            cmd /c "diskperf -y"
            cmd /c "sc config Audiosrv start= auto"
            cmd /c "sc start audiosrv"
            echo "Username: Administrator"
            echo "Password" @RDPfree" 
            Get-Localuser
